apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  activeDeadlineSeconds: 15
  template:
    spec:
      containers:
      - name: sleep
        image: mmussomele/sleep
      restartPolicy: Never
